# Stage 1 - Build
FROM node:18-alpine as build
WORKDIR /app
COPY ./SCIMLbot/package*.json ./
RUN npm install
COPY ./SCIMLbot/ ./
RUN npm run build

# Stage 2 - Serve
FROM nginx:alpine
COPY --from=build /app/dist/scimlbot/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
