version: '3.8'

services:
  bot-ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8080:80"
    depends_on:
      - bot-be

  bot-be:
    build:
      context: .
      dockerfile: Dockerfile.be
    ports:
      - "8000:8000"
